"""initial migration

Revision ID: f7f047acd47b
Revises: 
Create Date: 2025-10-16 06:15:01.496854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f047acd47b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oxi_services')
    op.drop_table('service')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('fid')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.create_table('service',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oxi_services',
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('service_icon', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('service_description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('service_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
